version: "3"
services:
  server:
    image: "sbcmel/apiserver"
    hostname: api
  frontend:
    image: "sbcmel/frontend"
    hostname: client
  nginx:
    image: "sbcmel/nginx-tech"
    hostname: nginx
    ports:
      - "80:80"
